name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cháº¡y má»—i khi cÃ³ commit má»›i vÃ o nhÃ¡nh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install wasm-pack ğŸ¦€
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Build WASM âš™ï¸
        run: wasm-pack build --target web
      - name: Prepare Deployment ğŸ“¦
        run: |
          cp -r pkg www/
      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: www
